application:
    name: Logistics Vessel coordinator
    id: l2l:coordinators:lvc:cbd8b7d0-8689-11e9-af93-e94a4331c552
    type: coordinator
    bussiness_key: lvc
    description : "Coordinator between vessel and logistics company"
    services:
      - xxFunction:
        trigger_events:
          - 
             topic_in: A_in
             type: SNS
             filter: none
          - 
            topic_default_in: topic_default_in
            type: SNS
            filter: none
            topic_default_out: topic_default_out